### ISSUE TITLE
Disable the warning message

### ISSUE THREAD

**Issue by byzheng** [efurlanm/mermaid-tw5#1]
Could we disable or auto close the warning message when we create a new graph? For example,

![image](https://user-images.githubusercontent.com/1657381/170805195-44ca1e19-7cd4-45ab-ad11-287cf1129a70.png)

**Comment by efurlanm** [comment]
Hi Zheng,

I'm not the author of the plugin, I just got what I was already ready, and updated the mermaid.js to the latest version. All credits are from the original authors:

http://gt6796c.github.io/
http://mermaid-js.github.io/

I have no idea how to eliminate this issue.
